name: {{cookiecutter.environment_name}}
channels:
  - conda-forge
  - defaults
dependencies:
  - arrow-cpp=11.0.0=h694c41f_13_cpu
  - attrs=22.2.0=pyh71513ae_0
  - aws-c-auth=0.6.26=hcaaecf5_1
  - aws-c-cal=0.5.21=hf54dd2f_2
  - aws-c-common=0.8.14=hb7f2c08_0
  - aws-c-compression=0.2.16=h99c63db_5
  - aws-c-event-stream=0.2.20=h0ae4c0f_4
  - aws-c-http=0.7.6=hcdd7835_0
  - aws-c-io=0.13.19=had634fe_3
  - aws-c-mqtt=0.8.6=ha4e05e3_12
  - aws-c-s3=0.2.7=hba8c00c_1
  - aws-c-sdkutils=0.1.8=h99c63db_0
  - aws-checksums=0.1.14=h99c63db_5
  - aws-crt-cpp=0.19.8=h8b21dc2_12
  - aws-sdk-cpp=1.10.57=h0d082ec_8
  - black=23.1.0=py311h6eed73b_0
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.18.1=h0d85af4_0
  - ca-certificates=2022.12.7=h033912b_0
  - cffi=1.15.1=py311ha86e640_3
  - cfgv=3.3.1=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_0
  - curl=7.88.1=h6df9250_1
  - distlib=0.3.6=pyhd8ed1ab_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - expat=2.5.0=hf0c8a7f_0
  - filelock=3.10.4=pyhd8ed1ab_0
  - flake8=6.0.0=pyhd8ed1ab_0
  - gettext=0.21.1=h8a4c099_0
  - gflags=2.2.2=hb1e8313_1004
  - git=2.40.0=pl5321h33fe9b8_1
  - glog=0.6.0=h8ac2a54_0
  - identify=2.5.22=pyhd8ed1ab_0
  - importlib-metadata=6.1.0=pyha770c72_0
  - interrogate=1.5.0=pyhd8ed1ab_0
  - isort=5.12.0=pyhd8ed1ab_1
  - krb5=1.20.1=h049b76e_0
  - libabseil=20230125.0=cxx17_hf0c8a7f_1
  - libarrow=11.0.0=h547aefa_13_cpu
  - libblas=3.9.0=16_osx64_openblas
  - libbrotlicommon=1.0.9=hb7f2c08_8
  - libbrotlidec=1.0.9=hb7f2c08_8
  - libbrotlienc=1.0.9=hb7f2c08_8
  - libcblas=3.9.0=16_osx64_openblas
  - libcrc32c=1.1.2=he49afe7_0
  - libcurl=7.88.1=h6df9250_1
  - libcxx=15.0.7=h71dddab_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libevent=2.1.10=h7d65743_4
  - libffi=3.4.2=h0d85af4_5
  - libgfortran=5.0.0=11_3_0_h97931a8_31
  - libgfortran5=12.2.0=he409387_31
  - libgoogle-cloud=2.8.0=h176059f_1
  - libgrpc=1.52.1=h5bc3d57_1
  - libiconv=1.17=hac89ed1_0
  - liblapack=3.9.0=16_osx64_openblas
  - libnghttp2=1.52.0=he2ab024_0
  - libopenblas=0.3.21=openmp_h429af6e_3
  - libprotobuf=3.21.12=hbc0c0cd_0
  - libsqlite=3.40.0=ha978bb4_0
  - libssh2=1.10.0=h47af595_3
  - libthrift=0.18.1=h16802d8_0
  - libutf8proc=2.8.0=hb7f2c08_0
  - libzlib=1.2.13=hfd90126_4
  - llvm-openmp=16.0.0=h61d9ccf_0
  - lz4-c=1.9.4=hf0c8a7f_0
  - mccabe=0.7.0=pyhd8ed1ab_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - ncurses=6.3=h96cf925_1
  - nodeenv=1.7.0=pyhd8ed1ab_0
  - numpy=1.24.2=py311ha9d2c9f_0
  - openpyxl=3.1.1=py311h5547dcb_0
  - openssl=3.1.0=hfd90126_0
  - orc=1.8.3=ha9d861c_0
  - packaging=23.0=pyhd8ed1ab_0
  - pandas=1.5.3=py311hd84f3f5_1
  - parquet-cpp=1.5.1=2
  - pathspec=0.11.1=pyhd8ed1ab_0
  - pcre2=10.40=h1c4e4bc_0
  - perl=5.32.1=2_h0d85af4_perl5
  - pip=23.0.1=pyhd8ed1ab_0
  - platformdirs=3.1.1=pyhd8ed1ab_0
  - pre-commit=3.2.0=pyha770c72_0
  - py=1.11.0=pyh6c4a22f_0
  - pyarrow=11.0.0=py311hb17b21d_13_cpu
  - pycodestyle=2.10.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyflakes=3.0.1=pyhd8ed1ab_0
  - python=3.11.0=he7542f4_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.11=3_cp311
  - pytz=2023.3=pyhd8ed1ab_0
  - pyyaml=6.0=py311h5547dcb_5
  - re2=2023.02.02=hf0c8a7f_0
  - readline=8.2=h9e318b2_1
  - setuptools=67.6.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h225ccf5_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tk=8.6.12=h5dbffcc_0
  - toml=0.10.2=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2023b=h71feb2d_0
  - ukkonen=1.0.1=py311hd2070f0_3
  - virtualenv=20.21.0=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xz=5.2.6=h775f41a_0
  - yaml=0.2.5=h0d85af4_2
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=hfd90126_4
  - zstd=1.5.2=hbc0c0cd_6
  - pip:
      - aiohttp==3.8.4
      - aiohttp-retry==2.8.3
      - aiosignal==1.3.1
      - amqp==5.1.1
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - arrow==1.2.3
      - async-timeout==4.0.2
      - asyncssh==2.13.1
      - atpublic==3.1.1
      - billiard==3.6.4.0
      - binaryornot==0.4.4
      - celery==5.2.7
      - certifi==2022.12.7
      - chardet==5.1.0
      - charset-normalizer==3.1.0
      - click-didyoumean==0.3.0
      - click-plugins==1.1.1
      - click-repl==0.2.0
      - configobj==5.0.8
      - cookiecutter==2.1.1
      - cryptography==40.0.2
      - dictdiffer==0.9.0
      - diskcache==5.6.1
      - distro==1.8.0
      - dpath==2.1.5
      - dulwich==0.21.5
      - dvc==2.56.0
      - dvc-data==0.47.5
      - dvc-http==2.30.2
      - dvc-objects==0.21.2
      - dvc-render==0.4.0
      - dvc-studio-client==0.9.0
      - dvc-task==0.2.1
      - flatten-dict==0.4.2
      - flufl-lock==7.1.1
      - frozenlist==1.3.3
      - fsspec==2023.5.0
      - funcy==2.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - grandalf==0.8
      - hydra-core==1.3.2
      - idna==3.4
      - iterative-telemetry==0.0.8
      - jinja2==3.1.2
      - jinja2-time==0.2.0
      - kombu==5.2.4
      - markdown-it-py==2.2.0
      - markupsafe==2.1.2
      - mdurl==0.1.2
      - multidict==6.0.4
      - nanotime==0.5.2
      - networkx==3.1
      - omegaconf==2.3.0
      - orjson==3.8.12
      - prompt-toolkit==3.0.38
      - psutil==5.9.5
      - pydot==1.4.2
      - pygit2==1.12.1
      - pygments==2.15.1
      - pygtrie==2.5.0
      - pyparsing==3.0.9
      - python-slugify==8.0.1
      - requests==2.28.2
      - rich==13.3.5
      - ruamel-yaml==0.17.24
      - ruamel-yaml-clib==0.2.7
      - scmrepo==1.0.3
      - shortuuid==1.0.11
      - shtab==1.6.1
      - smmap==5.0.0
      - sqltrie==0.3.1
      - text-unidecode==1.3
      - tomlkit==0.11.8
      - tqdm==4.65.0
      - urllib3==1.26.15
      - vine==5.0.0
      - voluptuous==0.13.1
      - wcwidth==0.2.6
      - yarl==1.9.2
      - zc-lockfile==3.0.post1
