name: datascience_template
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.18.1=h0d85af4_0
  - ca-certificates=2022.12.7=h033912b_0
  - cffi=1.15.1=py311ha86e640_3
  - cfgv=3.3.1=pyhd8ed1ab_0
  - curl=8.0.1=h1fead75_0
  - distlib=0.3.6=pyhd8ed1ab_0
  - expat=2.5.0=hf0c8a7f_0
  - filelock=3.10.4=pyhd8ed1ab_0
  - gettext=0.21.1=h8a4c099_0
  - git=2.40.0=pl5321h33fe9b8_1
  - identify=2.5.22=pyhd8ed1ab_0
  - importlib-metadata=6.1.0=pyha770c72_0
  - krb5=1.20.1=h049b76e_0
  - libcurl=8.0.1=h1fead75_0
  - libcxx=15.0.7=h71dddab_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libffi=3.4.2=h0d85af4_5
  - libiconv=1.17=hac89ed1_0
  - libnghttp2=1.52.0=he2ab024_0
  - libsqlite=3.40.0=ha978bb4_0
  - libssh2=1.10.0=h47af595_3
  - libzlib=1.2.13=hfd90126_4
  - ncurses=6.3=h96cf925_1
  - nodeenv=1.7.0=pyhd8ed1ab_0
  - openssl=3.1.0=hfd90126_0
  - pcre2=10.40=h1c4e4bc_0
  - perl=5.32.1=2_h0d85af4_perl5
  - pip=23.0.1=pyhd8ed1ab_0
  - platformdirs=3.1.1=pyhd8ed1ab_0
  - pre-commit=3.2.0=pyha770c72_0
  - pycparser=2.21=pyhd8ed1ab_0
  - python=3.11.0=he7542f4_1_cpython
  - python_abi=3.11=3_cp311
  - pyyaml=6.0=py311h5547dcb_5
  - readline=8.2=h9e318b2_1
  - setuptools=67.6.0=pyhd8ed1ab_0
  - tk=8.6.12=h5dbffcc_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2023b=h71feb2d_0
  - ukkonen=1.0.1=py311hd2070f0_3
  - virtualenv=20.21.0=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xz=5.2.6=h775f41a_0
  - yaml=0.2.5=h0d85af4_2
  - zipp=3.15.0=pyhd8ed1ab_0
  - zstd=1.5.2=hbc0c0cd_6
  - pip:
      - arrow==1.2.3
      - binaryornot==0.4.4
      - certifi==2022.12.7
      - chardet==5.1.0
      - charset-normalizer==3.1.0
      - click==8.1.3
      - cookiecutter==2.1.1
      - idna==3.4
      - jinja2==3.1.2
      - jinja2-time==0.2.0
      - markupsafe==2.1.2
      - python-dateutil==2.8.2
      - python-slugify==8.0.1
      - requests==2.28.2
      - six==1.16.0
      - text-unidecode==1.3
      - urllib3==1.26.15
prefix: /Users/rauldemaio/opt/anaconda3/envs/datascience_template
